### ISSUE TITLE
Getting an error when trying to start homebridge

### ISSUE THREAD

**Issue by bodenlaman** [dominick-han/homebridge-hdmi-cec#7]
Here is my log:

[2019-4-9 02:52:46] Error: spawn cec-client ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

My JSON file is also below:

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
	"ports": {
		"start": 52100,
		"end": 52150,
		"comment": "This section is used to control the range of ports that separate accessory (like camera or television) should be bind to."
	},
	"accessories": [{}],

	"platforms": [{
		"platform": "CEC",
		"sources": [{
				"name": "Raspberry Pi",
				"address": "2.0.0.0"
			},
			{
				"platform": "Camera-ffmpeg",
				"cameras": [{
					"name": "BasementCam",
					"videoConfig": {
						"source": "-f v4l2 -r 30 -s 1280x720 -i /dev/video0",
						"maxStreams": 2,
						"maxWidth": 1280,
						"maxHeight": 720,
						"maxFPS": 30,
						"vcodec": "h264_omx"
					}
				}]
			}
		]

	}]
}

**Comment by FabrizioCivic** [comment]
hi, i have the same error!!!

**Comment by dominick-han** [comment]
Do you guys have cec-client installed? Can you manually run “cec-client -d 8” (both of you 😂)

**Comment by bodenlaman** [comment]
I believe I do have it installed, but I'll try to run it manually.
